name: avatarify
region: pk
services:
  - environment_slug: node-js
    github:
      branch: master
      deploy_on_push: true
      repo: smash-96/Avatarify-api
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    name: avatarify
    routes:
      - path: /
    run_command: npm start
